name: tone_js
sdk: ">=1.15.0"
dependencies:
  js: any
  browser: any
  tekartik_test_menu:
    git:
      url: git://github.com/tekartik/tekartik_test_menu.dart
      ref: dart1
dev_dependencies:
  test: any
  dev_test: any