name: tekartik_tone_js
version: 0.2.0
description: tone js wrapper
environment:
  sdk: '>=2.0.0-dev.63 <3.0.0'
dependencies:
  js: any
  synchronized:
  tekartik_browser_utils:
    git:
      url: git://github.com/tekartik/browser_utils.dart
      ref: dart2
    version: '>=0.6.4'
dev_dependencies:
  tekartik_build_utils:
    git:
      url: git://github.com/tekartik/build_utils.dart
      ref: dart2
    version: '>=0.5.7'
  tekartik_test_menu_browser:
    git:
      url: git://github.com/tekartik/test_menu.dart
      ref: dart2
      path: test_menu_browser
    version: '>=0.1.0'
  test: '>=1.2.0'
  dev_test: '>=0.13.0-dev.1'
  build_runner: '>=0.10.1'
  build_test: '>=0.10.3'
  build_web_compilers: '>=0.4.2'